### PR TITLE
Add cloud build

### PR DESCRIPTION
**Pull request by timarney**

### CODE REVIEW

**Comment by maxneuvians** [comment]
You can actually set it up before merging because cloudbuild can run on a branch. Also I would need to set it up in my account as those keys are encrypted with my key (unless we used same naming) - I am happy to do that, unless you want to rep on that.

**Comment by timarney** [comment]
Did the crypto thing this a.m so will setup a trigger and see if it works.

**Comment by maxneuvians** [comment]
Nice!

**Comment by timarney** [comment]
🎉 
```
Step #1: PASS __tests__/status.test.js
Step #1: PASS __tests__/is-ready.test.js
Step #1: 
Step #1: Test Suites: 2 passed, 2 total
Step #1: Tests: 3 passed, 3 total
Step #1: Snapshots: 0 total
Step #1: Time: 2.75s
Step #1: Ran all test suites.
Finished Step #1
Starting Step #2 - "push_docker_hub"
Step #2 - "push_docker_hub": Already have image (with digest): gcr.io/cloud-builders/docker
Finished Step #2 - "push_docker_hub"
PUSH
DONE
```

**Pull request merged**
